[package]
name = "dprint-plugin-markdown"
description = "Markdown formatter for dprint."
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
license-file = "LICENSE"
edition = "2018"
homepage = "https://github.com/dprint/dprint-plugin-markdown"
repository = "https://github.com/dprint/dprint-plugin-markdown"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
dprint-core = "0.23.0"
pulldown-cmark = { version = "0.7", default-features = false }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
dprint-development = "0.2.0"
